/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Cliente;

import controlador.ControladorUsuario;
import controlador.MySQLDB;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Usuario;

/**
 *
 * @author vinic
 */
public class BuscarUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form Crear
     */
    private ControladorUsuario controlador;
    private DefaultTableModel modelotabla;

    public BuscarUsuario() {
        initComponents();
        controlador = new ControladorUsuario();
        modelotabla = new DefaultTableModel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel6 = new javax.swing.JPanel();
        buscarclientes = new javax.swing.JLabel();
        txtCedulaB = new javax.swing.JTextField();
        ingreseCedula = new javax.swing.JLabel();
        panelBuscarCliente = new javax.swing.JPanel();
        nombre2 = new javax.swing.JLabel();
        apillido2 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtApellidoB = new javax.swing.JTextField();
        txtNombreB = new javax.swing.JTextField();
        txtTelefonoB = new javax.swing.JTextField();
        telefono2 = new javax.swing.JLabel();
        direcion2 = new javax.swing.JLabel();
        txtDirecionB = new javax.swing.JTextField();
        direcion3 = new javax.swing.JLabel();
        txtContraB = new javax.swing.JPasswordField();
        buscar1 = new javax.swing.JButton();

        jPasswordField1.setText("jPasswordField1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buscarclientes.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        buscarclientes.setText("BUSCAR CLIENTES");
        jPanel6.add(buscarclientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 298, 37));

        txtCedulaB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaBKeyTyped(evt);
            }
        });
        jPanel6.add(txtCedulaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 64, 153, -1));

        ingreseCedula.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        ingreseCedula.setText("INGRESE CEDULA: ");
        jPanel6.add(ingreseCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 62, 164, 20));

        panelBuscarCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombre2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        nombre2.setText("NOMBRE: ");
        panelBuscarCliente.add(nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 24, 98, -1));

        apillido2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        apillido2.setText("APELLIDOS: ");
        panelBuscarCliente.add(apillido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 55, 98, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        panelBuscarCliente.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 24, -1, -1));

        txtApellidoB.setEditable(false);
        panelBuscarCliente.add(txtApellidoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 55, 168, -1));

        txtNombreB.setEditable(false);
        panelBuscarCliente.add(txtNombreB, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 24, 168, -1));

        txtTelefonoB.setEditable(false);
        panelBuscarCliente.add(txtTelefonoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 93, 168, -1));

        telefono2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        telefono2.setText("TELEFONO:");
        panelBuscarCliente.add(telefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 93, 98, -1));

        direcion2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        direcion2.setText("DIRECCION");
        panelBuscarCliente.add(direcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 131, 98, -1));

        txtDirecionB.setEditable(false);
        panelBuscarCliente.add(txtDirecionB, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 131, 168, -1));

        direcion3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        direcion3.setText("CONTRASEÑA:");
        panelBuscarCliente.add(direcion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 162, 146, -1));

        txtContraB.setEditable(false);
        panelBuscarCliente.add(txtContraB, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 160, -1));

        jPanel6.add(panelBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 300));

        buscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        buscar1.setText("BUSCAR");
        buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar1ActionPerformed(evt);
            }
        });
        jPanel6.add(buscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 15, 495, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCedulaBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaBKeyTyped
        if (evt.getKeyCode() != KeyEvent.VK_DELETE) {
            if (evt.getKeyChar() < '0' || evt.getKeyChar() > '9') {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtCedulaBKeyTyped

    private void buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar1ActionPerformed
        Usuario u = controlador.findByCedula(txtCedulaB.getText());
        if (u != null) {
            txtNombreB.setText(u.getNombre());
            txtApellidoB.setText(u.getApellido());
            txtTelefonoB.setText(u.getTelefono());
            txtDirecionB.setText(u.getDireccion());
            txtContraB.setText(u.getContracenia());
        } else {
            JOptionPane.showMessageDialog(this, "Usuario no econtrado");
            txtNombreB.setText("");
            txtApellidoB.setText("");
            txtTelefonoB.setText("");
            txtDirecionB.setText("");
            txtContraB.setText("");
        }
    }//GEN-LAST:event_buscar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apillido2;
    private javax.swing.JButton buscar1;
    private javax.swing.JLabel buscarclientes;
    private javax.swing.JLabel direcion2;
    private javax.swing.JLabel direcion3;
    private javax.swing.JLabel ingreseCedula;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel nombre2;
    private javax.swing.JPanel panelBuscarCliente;
    private javax.swing.JLabel telefono2;
    private javax.swing.JTextField txtApellidoB;
    private javax.swing.JTextField txtCedulaB;
    private javax.swing.JPasswordField txtContraB;
    private javax.swing.JTextField txtDirecionB;
    private javax.swing.JTextField txtNombreB;
    private javax.swing.JTextField txtTelefonoB;
    // End of variables declaration//GEN-END:variables
}
